version: '3'

services:
  probe-mongo-database:
    image: mongo:3.4.13
    container_name: probe-mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: elo7
      MONGO_INITDB_ROOT_PASSWORD: elo7
      MONGO_INITDB_DATABASE: probedb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  probe-cassandra-database:
    image: cassandra:3.11.5
    container_name: probe-cassandra-db
    restart: always
    ports:
      - 9042:9042
  probe-cassandra-init:
    image: cassandra:3.11.5
    container_name: probe-cassandra-db-init
    depends_on:
      - probe-cassandra-database
    volumes:
      - ./cassandra-init.cql:/cassandra-init.cql:ro
    command: bin/bash -c "echo Initializing cassandra schema... && sleep 30 && cqlsh -u cassandra -p cassandra -f cassandra-init.cql order-cassandra-db"